server {
  listen 1060 default_server;
  listen [::]:1060 default_server;
  root /usr/share/nginx/html;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html =404;
  }

  location ~ \.js {
    add_header Content-Type text/javascript;
  }
}

server {
    listen 443 ssl;
    ssl_certificate /etc/nginx/conf.d/cert/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/cert/server.key;

    location / {
        proxy_pass http://localhost:9001;
    }
}